# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guruntu.ui'
#
# Created: Tue Jan 16 09:13:28 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1378, 897)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(-10, 0, 1881, 1471))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_12 = QtGui.QWidget()
        self.tab_12.setObjectName(_fromUtf8("tab_12"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_12)
        self.groupBox_2.setGeometry(QtCore.QRect(500, 10, 401, 471))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.btnKaydet = QtGui.QPushButton(self.groupBox_2)
        self.btnKaydet.setGeometry(QtCore.QRect(30, 400, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnKaydet.setFont(font)
        self.btnKaydet.setObjectName(_fromUtf8("btnKaydet"))
        self.label_30 = QtGui.QLabel(self.groupBox_2)
        self.label_30.setGeometry(QtCore.QRect(350, 300, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setText(_fromUtf8(""))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.groupBox_16 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_16.setGeometry(QtCore.QRect(10, 30, 131, 171))
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.dlDundur = QtGui.QDial(self.groupBox_16)
        self.dlDundur.setGeometry(QtCore.QRect(10, 30, 100, 71))
        self.dlDundur.setMaximum(360)
        self.dlDundur.setPageStep(1)
        self.dlDundur.setInvertedAppearance(False)
        self.dlDundur.setInvertedControls(False)
        self.dlDundur.setWrapping(False)
        self.dlDundur.setNotchTarget(3.7)
        self.dlDundur.setNotchesVisible(True)
        self.dlDundur.setObjectName(_fromUtf8("dlDundur"))
        self.label_29 = QtGui.QLabel(self.groupBox_16)
        self.label_29.setGeometry(QtCore.QRect(50, 110, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.groupBox_17 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_17.setGeometry(QtCore.QRect(150, 30, 120, 171))
        self.groupBox_17.setObjectName(_fromUtf8("groupBox_17"))
        self.hsBulanklastir = QtGui.QSlider(self.groupBox_17)
        self.hsBulanklastir.setGeometry(QtCore.QRect(10, 50, 101, 51))
        self.hsBulanklastir.setMinimum(0)
        self.hsBulanklastir.setMaximum(100)
        self.hsBulanklastir.setSingleStep(2)
        self.hsBulanklastir.setOrientation(QtCore.Qt.Horizontal)
        self.hsBulanklastir.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.hsBulanklastir.setObjectName(_fromUtf8("hsBulanklastir"))
        self.groupBox_14 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_14.setGeometry(QtCore.QRect(280, 30, 111, 171))
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.btnGri = QtGui.QPushButton(self.groupBox_14)
        self.btnGri.setGeometry(QtCore.QRect(10, 20, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnGri.setFont(font)
        self.btnGri.setObjectName(_fromUtf8("btnGri"))
        self.btnIkili = QtGui.QPushButton(self.groupBox_14)
        self.btnIkili.setGeometry(QtCore.QRect(10, 60, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnIkili.setFont(font)
        self.btnIkili.setObjectName(_fromUtf8("btnIkili"))
        self.btnSifirla = QtGui.QPushButton(self.groupBox_14)
        self.btnSifirla.setGeometry(QtCore.QRect(10, 100, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnSifirla.setFont(font)
        self.btnSifirla.setObjectName(_fromUtf8("btnSifirla"))
        self.groupBox_18 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_18.setGeometry(QtCore.QRect(90, 240, 251, 141))
        self.groupBox_18.setObjectName(_fromUtf8("groupBox_18"))
        self.teBoyutGenislik = QtGui.QTextEdit(self.groupBox_18)
        self.teBoyutGenislik.setGeometry(QtCore.QRect(20, 40, 51, 31))
        self.teBoyutGenislik.setObjectName(_fromUtf8("teBoyutGenislik"))
        self.teBoyutYukseklik = QtGui.QTextEdit(self.groupBox_18)
        self.teBoyutYukseklik.setGeometry(QtCore.QRect(100, 40, 51, 31))
        self.teBoyutYukseklik.setObjectName(_fromUtf8("teBoyutYukseklik"))
        self.label_24 = QtGui.QLabel(self.groupBox_18)
        self.label_24.setGeometry(QtCore.QRect(20, 20, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.qsBoyutGenislik = QtGui.QSlider(self.groupBox_18)
        self.qsBoyutGenislik.setGeometry(QtCore.QRect(20, 90, 51, 22))
        self.qsBoyutGenislik.setMaximum(880)
        self.qsBoyutGenislik.setOrientation(QtCore.Qt.Horizontal)
        self.qsBoyutGenislik.setObjectName(_fromUtf8("qsBoyutGenislik"))
        self.qsBoyutYukseklik = QtGui.QSlider(self.groupBox_18)
        self.qsBoyutYukseklik.setGeometry(QtCore.QRect(160, 30, 22, 41))
        self.qsBoyutYukseklik.setAutoFillBackground(False)
        self.qsBoyutYukseklik.setMaximum(440)
        self.qsBoyutYukseklik.setOrientation(QtCore.Qt.Vertical)
        self.qsBoyutYukseklik.setTickPosition(QtGui.QSlider.NoTicks)
        self.qsBoyutYukseklik.setObjectName(_fromUtf8("qsBoyutYukseklik"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_12)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 10, 461, 471))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gvOrjinal = QtGui.QGraphicsView(self.groupBox_5)
        self.gvOrjinal.setGeometry(QtCore.QRect(20, 60, 421, 391))
        self.gvOrjinal.setObjectName(_fromUtf8("gvOrjinal"))
        self.btnResimYukle = QtGui.QPushButton(self.groupBox_5)
        self.btnResimYukle.setGeometry(QtCore.QRect(20, 20, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnResimYukle.setFont(font)
        self.btnResimYukle.setObjectName(_fromUtf8("btnResimYukle"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_12)
        self.groupBox_6.setGeometry(QtCore.QRect(910, 10, 451, 471))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gvSonuc = QtGui.QGraphicsView(self.groupBox_6)
        self.gvSonuc.setGeometry(QtCore.QRect(10, 20, 431, 431))
        self.gvSonuc.setObjectName(_fromUtf8("gvSonuc"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab_12)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 510, 591, 321))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.groupBox_13 = QtGui.QGroupBox(self.groupBox_7)
        self.groupBox_13.setGeometry(QtCore.QRect(20, 40, 561, 221))
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.btnPikselGoster = QtGui.QPushButton(self.groupBox_13)
        self.btnPikselGoster.setGeometry(QtCore.QRect(200, 140, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnPikselGoster.setFont(font)
        self.btnPikselGoster.setObjectName(_fromUtf8("btnPikselGoster"))
        self.label_65 = QtGui.QLabel(self.groupBox_13)
        self.label_65.setGeometry(QtCore.QRect(150, 90, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_65.setFont(font)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.tePixelYukseklik = QtGui.QTextEdit(self.groupBox_13)
        self.tePixelYukseklik.setGeometry(QtCore.QRect(220, 90, 41, 31))
        self.tePixelYukseklik.setObjectName(_fromUtf8("tePixelYukseklik"))
        self.label_66 = QtGui.QLabel(self.groupBox_13)
        self.label_66.setGeometry(QtCore.QRect(290, 90, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_66.setFont(font)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.tePixelGenislik = QtGui.QTextEdit(self.groupBox_13)
        self.tePixelGenislik.setGeometry(QtCore.QRect(360, 90, 41, 31))
        self.tePixelGenislik.setObjectName(_fromUtf8("tePixelGenislik"))
        self.label_27 = QtGui.QLabel(self.groupBox_13)
        self.label_27.setGeometry(QtCore.QRect(150, 30, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_43 = QtGui.QLabel(self.groupBox_7)
        self.label_43.setGeometry(QtCore.QRect(150, 270, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_43.setFont(font)
        self.label_43.setText(_fromUtf8(""))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.groupBox_15 = QtGui.QGroupBox(self.tab_12)
        self.groupBox_15.setGeometry(QtCore.QRect(620, 510, 741, 321))
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.gvOrjinalHistogram = QtGui.QGraphicsView(self.groupBox_15)
        self.gvOrjinalHistogram.setGeometry(QtCore.QRect(20, 100, 331, 192))
        self.gvOrjinalHistogram.setObjectName(_fromUtf8("gvOrjinalHistogram"))
        self.gvSonucHistogram = QtGui.QGraphicsView(self.groupBox_15)
        self.gvSonucHistogram.setGeometry(QtCore.QRect(360, 100, 331, 192))
        self.gvSonucHistogram.setObjectName(_fromUtf8("gvSonucHistogram"))
        self.label_23 = QtGui.QLabel(self.groupBox_15)
        self.label_23.setGeometry(QtCore.QRect(70, 80, 201, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_26 = QtGui.QLabel(self.groupBox_15)
        self.label_26.setGeometry(QtCore.QRect(400, 80, 201, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.btnHistogram = QtGui.QPushButton(self.groupBox_15)
        self.btnHistogram.setGeometry(QtCore.QRect(20, 30, 671, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnHistogram.setFont(font)
        self.btnHistogram.setObjectName(_fromUtf8("btnHistogram"))
        self.tabWidget.addTab(self.tab_12, _fromUtf8(""))
        self.tab_13 = QtGui.QWidget()
        self.tab_13.setObjectName(_fromUtf8("tab_13"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_13)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 20, 561, 701))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gvFiltreYuklenen = QtGui.QGraphicsView(self.groupBox_3)
        self.gvFiltreYuklenen.setGeometry(QtCore.QRect(20, 90, 511, 571))
        self.gvFiltreYuklenen.setObjectName(_fromUtf8("gvFiltreYuklenen"))
        self.btnResimYukle2 = QtGui.QPushButton(self.groupBox_3)
        self.btnResimYukle2.setGeometry(QtCore.QRect(20, 30, 511, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnResimYukle2.setFont(font)
        self.btnResimYukle2.setObjectName(_fromUtf8("btnResimYukle2"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_13)
        self.groupBox_4.setGeometry(QtCore.QRect(620, 110, 120, 471))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.btnCanny = QtGui.QPushButton(self.groupBox_4)
        self.btnCanny.setGeometry(QtCore.QRect(10, 60, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnCanny.setFont(font)
        self.btnCanny.setObjectName(_fromUtf8("btnCanny"))
        self.btnSobel = QtGui.QPushButton(self.groupBox_4)
        self.btnSobel.setGeometry(QtCore.QRect(10, 160, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnSobel.setFont(font)
        self.btnSobel.setObjectName(_fromUtf8("btnSobel"))
        self.btnPrewit = QtGui.QPushButton(self.groupBox_4)
        self.btnPrewit.setGeometry(QtCore.QRect(10, 260, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnPrewit.setFont(font)
        self.btnPrewit.setObjectName(_fromUtf8("btnPrewit"))
        self.btnTreshold = QtGui.QPushButton(self.groupBox_4)
        self.btnTreshold.setGeometry(QtCore.QRect(10, 360, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnTreshold.setFont(font)
        self.btnTreshold.setObjectName(_fromUtf8("btnTreshold"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab_13)
        self.groupBox_8.setGeometry(QtCore.QRect(770, 30, 571, 681))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gvFiltreIslem = QtGui.QGraphicsView(self.groupBox_8)
        self.gvFiltreIslem.setGeometry(QtCore.QRect(40, 90, 521, 571))
        self.gvFiltreIslem.setObjectName(_fromUtf8("gvFiltreIslem"))
        self.tabWidget.addTab(self.tab_13, _fromUtf8(""))
        self.tab_14 = QtGui.QWidget()
        self.tab_14.setObjectName(_fromUtf8("tab_14"))
        self.lb_sekil_4 = QtGui.QLabel(self.tab_14)
        self.lb_sekil_4.setGeometry(QtCore.QRect(460, 420, 701, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_sekil_4.setFont(font)
        self.lb_sekil_4.setText(_fromUtf8(""))
        self.lb_sekil_4.setObjectName(_fromUtf8("lb_sekil_4"))
        self.groupBox_9 = QtGui.QGroupBox(self.tab_14)
        self.groupBox_9.setGeometry(QtCore.QRect(20, 20, 591, 771))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gvLabelingYukle = QtGui.QGraphicsView(self.groupBox_9)
        self.gvLabelingYukle.setGeometry(QtCore.QRect(10, 80, 541, 551))
        self.gvLabelingYukle.setObjectName(_fromUtf8("gvLabelingYukle"))
        self.btnLabelingYukle = QtGui.QPushButton(self.groupBox_9)
        self.btnLabelingYukle.setGeometry(QtCore.QRect(10, 30, 541, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnLabelingYukle.setFont(font)
        self.btnLabelingYukle.setObjectName(_fromUtf8("btnLabelingYukle"))
        self.groupBox_10 = QtGui.QGroupBox(self.tab_14)
        self.groupBox_10.setGeometry(QtCore.QRect(760, 150, 581, 381))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.gvLabelingIslem = QtGui.QGraphicsView(self.groupBox_10)
        self.gvLabelingIslem.setGeometry(QtCore.QRect(50, 30, 511, 301))
        self.gvLabelingIslem.setObjectName(_fromUtf8("gvLabelingIslem"))
        self.groupBox_11 = QtGui.QGroupBox(self.tab_14)
        self.groupBox_11.setGeometry(QtCore.QRect(630, 270, 120, 101))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.btnLabeling = QtGui.QPushButton(self.groupBox_11)
        self.btnLabeling.setGeometry(QtCore.QRect(10, 30, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnLabeling.setFont(font)
        self.btnLabeling.setObjectName(_fromUtf8("btnLabeling"))
        self.groupBox_12 = QtGui.QGroupBox(self.tab_14)
        self.groupBox_12.setGeometry(QtCore.QRect(620, 560, 721, 241))
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.groupBox = QtGui.QGroupBox(self.groupBox_12)
        self.groupBox.setGeometry(QtCore.QRect(360, 30, 321, 121))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.rbtnKare = QtGui.QRadioButton(self.groupBox)
        self.rbtnKare.setGeometry(QtCore.QRect(60, 50, 51, 17))
        self.rbtnKare.setObjectName(_fromUtf8("rbtnKare"))
        self.rbtnDikdortgen = QtGui.QRadioButton(self.groupBox)
        self.rbtnDikdortgen.setGeometry(QtCore.QRect(170, 50, 91, 17))
        self.rbtnDikdortgen.setObjectName(_fromUtf8("rbtnDikdortgen"))
        self.groupBox_57 = QtGui.QGroupBox(self.groupBox_12)
        self.groupBox_57.setGeometry(QtCore.QRect(60, 30, 261, 121))
        self.groupBox_57.setObjectName(_fromUtf8("groupBox_57"))
        self.btnLabelingKarsilastir = QtGui.QPushButton(self.groupBox_57)
        self.btnLabelingKarsilastir.setGeometry(QtCore.QRect(60, 40, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnLabelingKarsilastir.setFont(font)
        self.btnLabelingKarsilastir.setObjectName(_fromUtf8("btnLabelingKarsilastir"))
        self.label_25 = QtGui.QLabel(self.groupBox_12)
        self.label_25.setGeometry(QtCore.QRect(60, 170, 121, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.lblKarsilastir = QtGui.QLabel(self.groupBox_12)
        self.lblKarsilastir.setGeometry(QtCore.QRect(190, 170, 501, 16))
        self.lblKarsilastir.setText(_fromUtf8(""))
        self.lblKarsilastir.setObjectName(_fromUtf8("lblKarsilastir"))
        self.groupBox_37 = QtGui.QGroupBox(self.tab_14)
        self.groupBox_37.setGeometry(QtCore.QRect(760, 30, 581, 80))
        self.groupBox_37.setObjectName(_fromUtf8("groupBox_37"))
        self.label_33 = QtGui.QLabel(self.groupBox_37)
        self.label_33.setGeometry(QtCore.QRect(110, 30, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.cbLabelingBulunan = QtGui.QComboBox(self.groupBox_37)
        self.cbLabelingBulunan.setGeometry(QtCore.QRect(300, 30, 151, 22))
        self.cbLabelingBulunan.setObjectName(_fromUtf8("cbLabelingBulunan"))
        self.tabWidget.addTab(self.tab_14, _fromUtf8(""))
        self.tab_15 = QtGui.QWidget()
        self.tab_15.setObjectName(_fromUtf8("tab_15"))
        self.groupBox_58 = QtGui.QGroupBox(self.tab_15)
        self.groupBox_58.setGeometry(QtCore.QRect(20, 20, 661, 671))
        self.groupBox_58.setObjectName(_fromUtf8("groupBox_58"))
        self.gvHistogramYukle = QtGui.QGraphicsView(self.groupBox_58)
        self.gvHistogramYukle.setGeometry(QtCore.QRect(19, 70, 621, 581))
        self.gvHistogramYukle.setObjectName(_fromUtf8("gvHistogramYukle"))
        self.btnHistogramYukle = QtGui.QPushButton(self.groupBox_58)
        self.btnHistogramYukle.setGeometry(QtCore.QRect(20, 20, 621, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnHistogramYukle.setFont(font)
        self.btnHistogramYukle.setObjectName(_fromUtf8("btnHistogramYukle"))
        self.groupBox_59 = QtGui.QGroupBox(self.tab_15)
        self.groupBox_59.setGeometry(QtCore.QRect(720, 30, 621, 571))
        self.groupBox_59.setObjectName(_fromUtf8("groupBox_59"))
        self.gvHistogramSonuc = QtGui.QGraphicsView(self.groupBox_59)
        self.gvHistogramSonuc.setGeometry(QtCore.QRect(30, 30, 571, 511))
        self.gvHistogramSonuc.setObjectName(_fromUtf8("gvHistogramSonuc"))
        self.groupBox_60 = QtGui.QGroupBox(self.tab_15)
        self.groupBox_60.setGeometry(QtCore.QRect(720, 620, 621, 71))
        self.groupBox_60.setObjectName(_fromUtf8("groupBox_60"))
        self.btnHistogramKarsilastir = QtGui.QPushButton(self.groupBox_60)
        self.btnHistogramKarsilastir.setGeometry(QtCore.QRect(40, 20, 541, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnHistogramKarsilastir.setFont(font)
        self.btnHistogramKarsilastir.setObjectName(_fromUtf8("btnHistogramKarsilastir"))
        self.groupBox_61 = QtGui.QGroupBox(self.tab_15)
        self.groupBox_61.setGeometry(QtCore.QRect(460, 700, 881, 101))
        self.groupBox_61.setObjectName(_fromUtf8("groupBox_61"))
        self.lblHistogramKarsilastir = QtGui.QLabel(self.groupBox_61)
        self.lblHistogramKarsilastir.setGeometry(QtCore.QRect(160, 50, 611, 31))
        self.lblHistogramKarsilastir.setText(_fromUtf8(""))
        self.lblHistogramKarsilastir.setObjectName(_fromUtf8("lblHistogramKarsilastir"))
        self.label_2 = QtGui.QLabel(self.groupBox_61)
        self.label_2.setGeometry(QtCore.QRect(40, 52, 111, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.tabWidget.addTab(self.tab_15, _fromUtf8(""))
        self.tab_16 = QtGui.QWidget()
        self.tab_16.setObjectName(_fromUtf8("tab_16"))
        self.groupBox_62 = QtGui.QGroupBox(self.tab_16)
        self.groupBox_62.setGeometry(QtCore.QRect(30, 660, 1331, 131))
        self.groupBox_62.setObjectName(_fromUtf8("groupBox_62"))
        self.btnGurultuBenzerlikHesapla = QtGui.QPushButton(self.groupBox_62)
        self.btnGurultuBenzerlikHesapla.setGeometry(QtCore.QRect(10, 50, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnGurultuBenzerlikHesapla.setFont(font)
        self.btnGurultuBenzerlikHesapla.setObjectName(_fromUtf8("btnGurultuBenzerlikHesapla"))
        self.lblSsim = QtGui.QLabel(self.groupBox_62)
        self.lblSsim.setGeometry(QtCore.QRect(410, 50, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lblSsim.setFont(font)
        self.lblSsim.setObjectName(_fromUtf8("lblSsim"))
        self.lblMse = QtGui.QLabel(self.groupBox_62)
        self.lblMse.setGeometry(QtCore.QRect(950, 50, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lblMse.setFont(font)
        self.lblMse.setObjectName(_fromUtf8("lblMse"))
        self.groupBox_63 = QtGui.QGroupBox(self.tab_16)
        self.groupBox_63.setGeometry(QtCore.QRect(30, 20, 491, 621))
        self.groupBox_63.setObjectName(_fromUtf8("groupBox_63"))
        self.btnGurultuYukle = QtGui.QPushButton(self.groupBox_63)
        self.btnGurultuYukle.setGeometry(QtCore.QRect(20, 20, 451, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnGurultuYukle.setFont(font)
        self.btnGurultuYukle.setObjectName(_fromUtf8("btnGurultuYukle"))
        self.gvGurultuYukle = QtGui.QGraphicsView(self.groupBox_63)
        self.gvGurultuYukle.setGeometry(QtCore.QRect(19, 70, 451, 511))
        self.gvGurultuYukle.setObjectName(_fromUtf8("gvGurultuYukle"))
        self.groupBox_64 = QtGui.QGroupBox(self.tab_16)
        self.groupBox_64.setGeometry(QtCore.QRect(530, 20, 261, 621))
        self.groupBox_64.setObjectName(_fromUtf8("groupBox_64"))
        self.btnGurultuOlustur = QtGui.QPushButton(self.groupBox_64)
        self.btnGurultuOlustur.setGeometry(QtCore.QRect(50, 120, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnGurultuOlustur.setFont(font)
        self.btnGurultuOlustur.setObjectName(_fromUtf8("btnGurultuOlustur"))
        self.hsGurultuOlustur = QtGui.QSlider(self.groupBox_64)
        self.hsGurultuOlustur.setGeometry(QtCore.QRect(60, 240, 160, 22))
        self.hsGurultuOlustur.setMaximum(100)
        self.hsGurultuOlustur.setOrientation(QtCore.Qt.Horizontal)
        self.hsGurultuOlustur.setObjectName(_fromUtf8("hsGurultuOlustur"))
        self.label = QtGui.QLabel(self.groupBox_64)
        self.label.setGeometry(QtCore.QRect(50, 290, 91, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.lblGurultu = QtGui.QLabel(self.groupBox_64)
        self.lblGurultu.setGeometry(QtCore.QRect(160, 290, 71, 20))
        self.lblGurultu.setText(_fromUtf8(""))
        self.lblGurultu.setObjectName(_fromUtf8("lblGurultu"))
        self.groupBox_65 = QtGui.QGroupBox(self.tab_16)
        self.groupBox_65.setGeometry(QtCore.QRect(820, 20, 541, 621))
        self.groupBox_65.setObjectName(_fromUtf8("groupBox_65"))
        self.gvGurultuSonuc = QtGui.QGraphicsView(self.groupBox_65)
        self.gvGurultuSonuc.setGeometry(QtCore.QRect(30, 90, 491, 501))
        self.gvGurultuSonuc.setObjectName(_fromUtf8("gvGurultuSonuc"))
        self.tabWidget.addTab(self.tab_16, _fromUtf8(""))
        self.tab_17 = QtGui.QWidget()
        self.tab_17.setObjectName(_fromUtf8("tab_17"))
        self.groupBox_66 = QtGui.QGroupBox(self.tab_17)
        self.groupBox_66.setGeometry(QtCore.QRect(30, 20, 511, 391))
        self.groupBox_66.setObjectName(_fromUtf8("groupBox_66"))
        self.btnMantikYukle1Resim = QtGui.QPushButton(self.groupBox_66)
        self.btnMantikYukle1Resim.setGeometry(QtCore.QRect(20, 20, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMantikYukle1Resim.setFont(font)
        self.btnMantikYukle1Resim.setObjectName(_fromUtf8("btnMantikYukle1Resim"))
        self.gvMantik1Yukle = QtGui.QGraphicsView(self.groupBox_66)
        self.gvMantik1Yukle.setGeometry(QtCore.QRect(20, 60, 471, 311))
        self.gvMantik1Yukle.setObjectName(_fromUtf8("gvMantik1Yukle"))
        self.groupBox_68 = QtGui.QGroupBox(self.tab_17)
        self.groupBox_68.setGeometry(QtCore.QRect(570, 300, 171, 241))
        self.groupBox_68.setObjectName(_fromUtf8("groupBox_68"))
        self.lb_ssim_11 = QtGui.QLabel(self.groupBox_68)
        self.lb_ssim_11.setGeometry(QtCore.QRect(20, 40, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_ssim_11.setFont(font)
        self.lb_ssim_11.setObjectName(_fromUtf8("lb_ssim_11"))
        self.cbMantik = QtGui.QComboBox(self.groupBox_68)
        self.cbMantik.setGeometry(QtCore.QRect(30, 90, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.cbMantik.setFont(font)
        self.cbMantik.setObjectName(_fromUtf8("cbMantik"))
        self.cbMantik.addItem(_fromUtf8(""))
        self.cbMantik.addItem(_fromUtf8(""))
        self.cbMantik.addItem(_fromUtf8(""))
        self.cbMantik.addItem(_fromUtf8(""))
        self.cbMantik.addItem(_fromUtf8(""))
        self.btnMantikGoster = QtGui.QPushButton(self.groupBox_68)
        self.btnMantikGoster.setGeometry(QtCore.QRect(10, 170, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMantikGoster.setFont(font)
        self.btnMantikGoster.setObjectName(_fromUtf8("btnMantikGoster"))
        self.groupBox_69 = QtGui.QGroupBox(self.tab_17)
        self.groupBox_69.setGeometry(QtCore.QRect(780, 20, 581, 791))
        self.groupBox_69.setObjectName(_fromUtf8("groupBox_69"))
        self.gvMantikSonuc = QtGui.QGraphicsView(self.groupBox_69)
        self.gvMantikSonuc.setGeometry(QtCore.QRect(20, 40, 541, 711))
        self.gvMantikSonuc.setObjectName(_fromUtf8("gvMantikSonuc"))
        self.groupBox_67 = QtGui.QGroupBox(self.tab_17)
        self.groupBox_67.setGeometry(QtCore.QRect(30, 430, 511, 391))
        self.groupBox_67.setObjectName(_fromUtf8("groupBox_67"))
        self.btnMantikYukle2Resim = QtGui.QPushButton(self.groupBox_67)
        self.btnMantikYukle2Resim.setGeometry(QtCore.QRect(20, 20, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMantikYukle2Resim.setFont(font)
        self.btnMantikYukle2Resim.setObjectName(_fromUtf8("btnMantikYukle2Resim"))
        self.gvMantik2Yukle = QtGui.QGraphicsView(self.groupBox_67)
        self.gvMantik2Yukle.setGeometry(QtCore.QRect(20, 60, 471, 301))
        self.gvMantik2Yukle.setObjectName(_fromUtf8("gvMantik2Yukle"))
        self.tabWidget.addTab(self.tab_17, _fromUtf8(""))
        self.tab_18 = QtGui.QWidget()
        self.tab_18.setObjectName(_fromUtf8("tab_18"))
        self.groupBox_70 = QtGui.QGroupBox(self.tab_18)
        self.groupBox_70.setGeometry(QtCore.QRect(30, 40, 501, 711))
        self.groupBox_70.setObjectName(_fromUtf8("groupBox_70"))
        self.btnErosionYukle = QtGui.QPushButton(self.groupBox_70)
        self.btnErosionYukle.setGeometry(QtCore.QRect(20, 40, 451, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnErosionYukle.setFont(font)
        self.btnErosionYukle.setObjectName(_fromUtf8("btnErosionYukle"))
        self.gvErosionYukle = QtGui.QGraphicsView(self.groupBox_70)
        self.gvErosionYukle.setGeometry(QtCore.QRect(20, 90, 441, 551))
        self.gvErosionYukle.setObjectName(_fromUtf8("gvErosionYukle"))
        self.groupBox_71 = QtGui.QGroupBox(self.tab_18)
        self.groupBox_71.setGeometry(QtCore.QRect(550, 230, 281, 211))
        self.groupBox_71.setObjectName(_fromUtf8("groupBox_71"))
        self.btnDilation = QtGui.QPushButton(self.groupBox_71)
        self.btnDilation.setGeometry(QtCore.QRect(20, 50, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnDilation.setFont(font)
        self.btnDilation.setObjectName(_fromUtf8("btnDilation"))
        self.btnErosion = QtGui.QPushButton(self.groupBox_71)
        self.btnErosion.setGeometry(QtCore.QRect(20, 120, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnErosion.setFont(font)
        self.btnErosion.setObjectName(_fromUtf8("btnErosion"))
        self.groupBox_72 = QtGui.QGroupBox(self.tab_18)
        self.groupBox_72.setGeometry(QtCore.QRect(849, 50, 501, 701))
        self.groupBox_72.setObjectName(_fromUtf8("groupBox_72"))
        self.gvErosionSonuc = QtGui.QGraphicsView(self.groupBox_72)
        self.gvErosionSonuc.setGeometry(QtCore.QRect(20, 60, 461, 561))
        self.gvErosionSonuc.setObjectName(_fromUtf8("gvErosionSonuc"))
        self.tabWidget.addTab(self.tab_18, _fromUtf8(""))
        self.tab_19 = QtGui.QWidget()
        self.tab_19.setObjectName(_fromUtf8("tab_19"))
        self.groupBox_19 = QtGui.QGroupBox(self.tab_19)
        self.groupBox_19.setGeometry(QtCore.QRect(20, 10, 371, 401))
        self.groupBox_19.setObjectName(_fromUtf8("groupBox_19"))
        self.gvTemlateYukle = QtGui.QGraphicsView(self.groupBox_19)
        self.gvTemlateYukle.setGeometry(QtCore.QRect(10, 60, 341, 331))
        self.gvTemlateYukle.setObjectName(_fromUtf8("gvTemlateYukle"))
        self.btnTemplateYukle = QtGui.QPushButton(self.groupBox_19)
        self.btnTemplateYukle.setGeometry(QtCore.QRect(10, 20, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnTemplateYukle.setFont(font)
        self.btnTemplateYukle.setObjectName(_fromUtf8("btnTemplateYukle"))
        self.groupBox_21 = QtGui.QGroupBox(self.tab_19)
        self.groupBox_21.setGeometry(QtCore.QRect(700, 220, 641, 211))
        self.groupBox_21.setObjectName(_fromUtf8("groupBox_21"))
        self.gvCcoeffNormed2 = QtGui.QGraphicsView(self.groupBox_21)
        self.gvCcoeffNormed2.setGeometry(QtCore.QRect(220, 20, 201, 151))
        self.gvCcoeffNormed2.setObjectName(_fromUtf8("gvCcoeffNormed2"))
        self.gvCcoeffNormed3 = QtGui.QGraphicsView(self.groupBox_21)
        self.gvCcoeffNormed3.setGeometry(QtCore.QRect(430, 20, 201, 151))
        self.gvCcoeffNormed3.setObjectName(_fromUtf8("gvCcoeffNormed3"))
        self.gvCcoeffNormed1 = QtGui.QGraphicsView(self.groupBox_21)
        self.gvCcoeffNormed1.setGeometry(QtCore.QRect(10, 20, 201, 151))
        self.gvCcoeffNormed1.setObjectName(_fromUtf8("gvCcoeffNormed1"))
        self.label_4 = QtGui.QLabel(self.groupBox_21)
        self.label_4.setGeometry(QtCore.QRect(20, 180, 131, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lblccoeffNormed = QtGui.QLabel(self.groupBox_21)
        self.lblccoeffNormed.setGeometry(QtCore.QRect(160, 180, 421, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lblccoeffNormed.setFont(font)
        self.lblccoeffNormed.setText(_fromUtf8(""))
        self.lblccoeffNormed.setObjectName(_fromUtf8("lblccoeffNormed"))
        self.groupBox_25 = QtGui.QGroupBox(self.tab_19)
        self.groupBox_25.setGeometry(QtCore.QRect(700, 660, 641, 211))
        self.groupBox_25.setObjectName(_fromUtf8("groupBox_25"))
        self.gvCcorrNormed3 = QtGui.QGraphicsView(self.groupBox_25)
        self.gvCcorrNormed3.setGeometry(QtCore.QRect(430, 20, 201, 151))
        self.gvCcorrNormed3.setObjectName(_fromUtf8("gvCcorrNormed3"))
        self.gvCcorrNormed2 = QtGui.QGraphicsView(self.groupBox_25)
        self.gvCcorrNormed2.setGeometry(QtCore.QRect(220, 20, 201, 151))
        self.gvCcorrNormed2.setObjectName(_fromUtf8("gvCcorrNormed2"))
        self.gvCcorrNormed1 = QtGui.QGraphicsView(self.groupBox_25)
        self.gvCcorrNormed1.setGeometry(QtCore.QRect(10, 20, 201, 151))
        self.gvCcorrNormed1.setObjectName(_fromUtf8("gvCcorrNormed1"))
        self.label_5 = QtGui.QLabel(self.groupBox_25)
        self.label_5.setGeometry(QtCore.QRect(20, 180, 131, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lblccorrNormed = QtGui.QLabel(self.groupBox_25)
        self.lblccorrNormed.setGeometry(QtCore.QRect(160, 180, 421, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lblccorrNormed.setFont(font)
        self.lblccorrNormed.setText(_fromUtf8(""))
        self.lblccorrNormed.setObjectName(_fromUtf8("lblccorrNormed"))
        self.groupBox_28 = QtGui.QGroupBox(self.tab_19)
        self.groupBox_28.setGeometry(QtCore.QRect(20, 420, 651, 231))
        self.groupBox_28.setObjectName(_fromUtf8("groupBox_28"))
        self.gvSqdiff1 = QtGui.QGraphicsView(self.groupBox_28)
        self.gvSqdiff1.setGeometry(QtCore.QRect(10, 20, 201, 161))
        self.gvSqdiff1.setObjectName(_fromUtf8("gvSqdiff1"))
        self.gvSqdiff3 = QtGui.QGraphicsView(self.groupBox_28)
        self.gvSqdiff3.setGeometry(QtCore.QRect(430, 20, 201, 161))
        self.gvSqdiff3.setObjectName(_fromUtf8("gvSqdiff3"))
        self.gvSqdiff2 = QtGui.QGraphicsView(self.groupBox_28)
        self.gvSqdiff2.setGeometry(QtCore.QRect(220, 20, 201, 161))
        self.gvSqdiff2.setObjectName(_fromUtf8("gvSqdiff2"))
        self.label_8 = QtGui.QLabel(self.groupBox_28)
        self.label_8.setGeometry(QtCore.QRect(10, 190, 131, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lblsqdiff = QtGui.QLabel(self.groupBox_28)
        self.lblsqdiff.setGeometry(QtCore.QRect(150, 190, 431, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lblsqdiff.setFont(font)
        self.lblsqdiff.setText(_fromUtf8(""))
        self.lblsqdiff.setObjectName(_fromUtf8("lblsqdiff"))
        self.groupBox_22 = QtGui.QGroupBox(self.tab_19)
        self.groupBox_22.setGeometry(QtCore.QRect(400, 10, 261, 401))
        self.groupBox_22.setObjectName(_fromUtf8("groupBox_22"))
        self.label_21 = QtGui.QLabel(self.groupBox_22)
        self.label_21.setGeometry(QtCore.QRect(20, 30, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.groupBox_22)
        self.label_22.setGeometry(QtCore.QRect(20, 80, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.cbGuruntuSec = QtGui.QComboBox(self.groupBox_22)
        self.cbGuruntuSec.setGeometry(QtCore.QRect(20, 50, 211, 22))
        self.cbGuruntuSec.setObjectName(_fromUtf8("cbGuruntuSec"))
        self.btnTemplate = QtGui.QPushButton(self.groupBox_22)
        self.btnTemplate.setGeometry(QtCore.QRect(20, 320, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnTemplate.setFont(font)
        self.btnTemplate.setObjectName(_fromUtf8("btnTemplate"))
        self.gvTemplateBulunan = QtGui.QGraphicsView(self.groupBox_22)
        self.gvTemplateBulunan.setGeometry(QtCore.QRect(20, 100, 211, 200))
        self.gvTemplateBulunan.setObjectName(_fromUtf8("gvTemplateBulunan"))
        self.groupBox_27 = QtGui.QGroupBox(self.tab_19)
        self.groupBox_27.setGeometry(QtCore.QRect(700, 10, 641, 211))
        self.groupBox_27.setObjectName(_fromUtf8("groupBox_27"))
        self.gp_2 = QtGui.QGraphicsView(self.groupBox_27)
        self.gp_2.setGeometry(QtCore.QRect(570, 380, 200, 200))
        self.gp_2.setObjectName(_fromUtf8("gp_2"))
        self.gp_11 = QtGui.QGraphicsView(self.groupBox_27)
        self.gp_11.setGeometry(QtCore.QRect(370, 380, 200, 200))
        self.gp_11.setObjectName(_fromUtf8("gp_11"))
        self.label_32 = QtGui.QLabel(self.groupBox_27)
        self.label_32.setGeometry(QtCore.QRect(840, 130, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gp_1 = QtGui.QGraphicsView(self.groupBox_27)
        self.gp_1.setGeometry(QtCore.QRect(170, 380, 200, 200))
        self.gp_1.setObjectName(_fromUtf8("gp_1"))
        self.gvCcoeff3 = QtGui.QGraphicsView(self.groupBox_27)
        self.gvCcoeff3.setGeometry(QtCore.QRect(430, 20, 201, 151))
        self.gvCcoeff3.setObjectName(_fromUtf8("gvCcoeff3"))
        self.gvCcoeff2 = QtGui.QGraphicsView(self.groupBox_27)
        self.gvCcoeff2.setGeometry(QtCore.QRect(220, 20, 201, 151))
        self.gvCcoeff2.setObjectName(_fromUtf8("gvCcoeff2"))
        self.gvCcoeff1 = QtGui.QGraphicsView(self.groupBox_27)
        self.gvCcoeff1.setGeometry(QtCore.QRect(10, 20, 201, 151))
        self.gvCcoeff1.setObjectName(_fromUtf8("gvCcoeff1"))
        self.label_7 = QtGui.QLabel(self.groupBox_27)
        self.label_7.setGeometry(QtCore.QRect(10, 180, 131, 31))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lblccoeff = QtGui.QLabel(self.groupBox_27)
        self.lblccoeff.setGeometry(QtCore.QRect(150, 180, 431, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lblccoeff.setFont(font)
        self.lblccoeff.setText(_fromUtf8(""))
        self.lblccoeff.setObjectName(_fromUtf8("lblccoeff"))
        self.groupBox_26 = QtGui.QGroupBox(self.tab_19)
        self.groupBox_26.setGeometry(QtCore.QRect(700, 430, 641, 221))
        self.groupBox_26.setObjectName(_fromUtf8("groupBox_26"))
        self.gvCcorr1 = QtGui.QGraphicsView(self.groupBox_26)
        self.gvCcorr1.setGeometry(QtCore.QRect(10, 20, 201, 161))
        self.gvCcorr1.setObjectName(_fromUtf8("gvCcorr1"))
        self.gvCcorr3 = QtGui.QGraphicsView(self.groupBox_26)
        self.gvCcorr3.setGeometry(QtCore.QRect(430, 20, 201, 161))
        self.gvCcorr3.setObjectName(_fromUtf8("gvCcorr3"))
        self.gvCcorr2 = QtGui.QGraphicsView(self.groupBox_26)
        self.gvCcorr2.setGeometry(QtCore.QRect(220, 20, 201, 161))
        self.gvCcorr2.setObjectName(_fromUtf8("gvCcorr2"))
        self.lbl = QtGui.QLabel(self.groupBox_26)
        self.lbl.setGeometry(QtCore.QRect(20, 190, 131, 21))
        self.lbl.setObjectName(_fromUtf8("lbl"))
        self.lblccorr = QtGui.QLabel(self.groupBox_26)
        self.lblccorr.setGeometry(QtCore.QRect(160, 190, 421, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lblccorr.setFont(font)
        self.lblccorr.setText(_fromUtf8(""))
        self.lblccorr.setObjectName(_fromUtf8("lblccorr"))
        self.groupBox_20 = QtGui.QGroupBox(self.tab_19)
        self.groupBox_20.setGeometry(QtCore.QRect(20, 660, 651, 211))
        self.groupBox_20.setObjectName(_fromUtf8("groupBox_20"))
        self.gvSqdiffNormed2 = QtGui.QGraphicsView(self.groupBox_20)
        self.gvSqdiffNormed2.setGeometry(QtCore.QRect(220, 20, 201, 151))
        self.gvSqdiffNormed2.setObjectName(_fromUtf8("gvSqdiffNormed2"))
        self.gvSqdiffNormed1 = QtGui.QGraphicsView(self.groupBox_20)
        self.gvSqdiffNormed1.setGeometry(QtCore.QRect(10, 20, 201, 151))
        self.gvSqdiffNormed1.setObjectName(_fromUtf8("gvSqdiffNormed1"))
        self.gvSqdiffNormed3 = QtGui.QGraphicsView(self.groupBox_20)
        self.gvSqdiffNormed3.setGeometry(QtCore.QRect(430, 20, 201, 151))
        self.gvSqdiffNormed3.setObjectName(_fromUtf8("gvSqdiffNormed3"))
        self.label_3 = QtGui.QLabel(self.groupBox_20)
        self.label_3.setGeometry(QtCore.QRect(10, 180, 131, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lblsqdiffNormed = QtGui.QLabel(self.groupBox_20)
        self.lblsqdiffNormed.setGeometry(QtCore.QRect(140, 180, 351, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lblsqdiffNormed.setFont(font)
        self.lblsqdiffNormed.setText(_fromUtf8(""))
        self.lblsqdiffNormed.setObjectName(_fromUtf8("lblsqdiffNormed"))
        self.tabWidget.addTab(self.tab_19, _fromUtf8(""))
        self.tab_20 = QtGui.QWidget()
        self.tab_20.setObjectName(_fromUtf8("tab_20"))
        self.groupBox_56 = QtGui.QGroupBox(self.tab_20)
        self.groupBox_56.setGeometry(QtCore.QRect(30, 10, 571, 851))
        self.groupBox_56.setObjectName(_fromUtf8("groupBox_56"))
        self.gvYuzTanimaYukle1 = QtGui.QGraphicsView(self.groupBox_56)
        self.gvYuzTanimaYukle1.setGeometry(QtCore.QRect(20, 70, 501, 421))
        self.gvYuzTanimaYukle1.setObjectName(_fromUtf8("gvYuzTanimaYukle1"))
        self.groupBox_90 = QtGui.QGroupBox(self.groupBox_56)
        self.groupBox_90.setGeometry(QtCore.QRect(20, 570, 181, 181))
        self.groupBox_90.setObjectName(_fromUtf8("groupBox_90"))
        self.btnYuzTanimaKisiBul = QtGui.QPushButton(self.groupBox_90)
        self.btnYuzTanimaKisiBul.setGeometry(QtCore.QRect(30, 60, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnYuzTanimaKisiBul.setFont(font)
        self.btnYuzTanimaKisiBul.setObjectName(_fromUtf8("btnYuzTanimaKisiBul"))
        self.groupBox_93 = QtGui.QGroupBox(self.groupBox_56)
        self.groupBox_93.setGeometry(QtCore.QRect(210, 580, 331, 171))
        self.groupBox_93.setObjectName(_fromUtf8("groupBox_93"))
        self.btnYuzIsimKaydet = QtGui.QPushButton(self.groupBox_93)
        self.btnYuzIsimKaydet.setGeometry(QtCore.QRect(190, 20, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnYuzIsimKaydet.setFont(font)
        self.btnYuzIsimKaydet.setObjectName(_fromUtf8("btnYuzIsimKaydet"))
        self.btnYuzEkleme = QtGui.QPushButton(self.groupBox_93)
        self.btnYuzEkleme.setGeometry(QtCore.QRect(190, 70, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnYuzEkleme.setFont(font)
        self.btnYuzEkleme.setObjectName(_fromUtf8("btnYuzEkleme"))
        self.leKaydedilecekIsim = QtGui.QLineEdit(self.groupBox_93)
        self.leKaydedilecekIsim.setGeometry(QtCore.QRect(10, 40, 171, 20))
        self.leKaydedilecekIsim.setObjectName(_fromUtf8("leKaydedilecekIsim"))
        self.btnYuzTanimaYukle1 = QtGui.QPushButton(self.groupBox_56)
        self.btnYuzTanimaYukle1.setGeometry(QtCore.QRect(20, 20, 501, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnYuzTanimaYukle1.setFont(font)
        self.btnYuzTanimaYukle1.setObjectName(_fromUtf8("btnYuzTanimaYukle1"))
        self.groupBox_89 = QtGui.QGroupBox(self.tab_20)
        self.groupBox_89.setGeometry(QtCore.QRect(590, 10, 761, 851))
        self.groupBox_89.setObjectName(_fromUtf8("groupBox_89"))
        self.label_42 = QtGui.QLabel(self.groupBox_89)
        self.label_42.setGeometry(QtCore.QRect(480, 310, 331, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_42.setFont(font)
        self.label_42.setText(_fromUtf8(""))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gvYuzTanimaYukle2 = QtGui.QGraphicsView(self.groupBox_89)
        self.gvYuzTanimaYukle2.setGeometry(QtCore.QRect(30, 70, 701, 400))
        self.gvYuzTanimaYukle2.setObjectName(_fromUtf8("gvYuzTanimaYukle2"))
        self.groupBox_92 = QtGui.QGroupBox(self.groupBox_89)
        self.groupBox_92.setGeometry(QtCore.QRect(90, 570, 231, 181))
        self.groupBox_92.setObjectName(_fromUtf8("groupBox_92"))
        self.btnKisiBul = QtGui.QPushButton(self.groupBox_92)
        self.btnKisiBul.setGeometry(QtCore.QRect(60, 70, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnKisiBul.setFont(font)
        self.btnKisiBul.setObjectName(_fromUtf8("btnKisiBul"))
        self.label_9 = QtGui.QLabel(self.groupBox_89)
        self.label_9.setGeometry(QtCore.QRect(30, 790, 41, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lblUyari = QtGui.QLabel(self.groupBox_89)
        self.lblUyari.setGeometry(QtCore.QRect(80, 790, 561, 20))
        self.lblUyari.setText(_fromUtf8(""))
        self.lblUyari.setObjectName(_fromUtf8("lblUyari"))
        self.groupBox_91 = QtGui.QGroupBox(self.groupBox_89)
        self.groupBox_91.setGeometry(QtCore.QRect(350, 570, 351, 181))
        self.groupBox_91.setObjectName(_fromUtf8("groupBox_91"))
        self.gvYuzTanimaBulunanYuzler = QtGui.QGraphicsView(self.groupBox_91)
        self.gvYuzTanimaBulunanYuzler.setGeometry(QtCore.QRect(110, 50, 100, 100))
        self.gvYuzTanimaBulunanYuzler.setObjectName(_fromUtf8("gvYuzTanimaBulunanYuzler"))
        self.cbYuzTanimaBulunanYuzler = QtGui.QComboBox(self.groupBox_91)
        self.cbYuzTanimaBulunanYuzler.setGeometry(QtCore.QRect(90, 20, 141, 22))
        self.cbYuzTanimaBulunanYuzler.setObjectName(_fromUtf8("cbYuzTanimaBulunanYuzler"))
        self.btnYuzTanimaYukle2 = QtGui.QPushButton(self.groupBox_89)
        self.btnYuzTanimaYukle2.setGeometry(QtCore.QRect(30, 20, 701, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnYuzTanimaYukle2.setFont(font)
        self.btnYuzTanimaYukle2.setObjectName(_fromUtf8("btnYuzTanimaYukle2"))
        self.tabWidget.addTab(self.tab_20, _fromUtf8(""))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(8)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Temel İşlemler", None))
        self.btnKaydet.setText(_translate("Dialog", "Kaydet", None))
        self.groupBox_16.setTitle(_translate("Dialog", "Döndürme", None))
        self.label_29.setText(_translate("Dialog", "0", None))
        self.groupBox_17.setTitle(_translate("Dialog", "Bulanıklaştırma", None))
        self.groupBox_14.setTitle(_translate("Dialog", "Görüntü İşlemleri", None))
        self.btnGri.setText(_translate("Dialog", "Gri", None))
        self.btnIkili.setText(_translate("Dialog", "İkili", None))
        self.btnSifirla.setText(_translate("Dialog", "Sıfırla", None))
        self.groupBox_18.setTitle(_translate("Dialog", "Boyut Bilgisi Ve  Yeniden Boyutlandırma ", None))
        self.label_24.setText(_translate("Dialog", "Genişlik         Yükseklik", None))
        self.groupBox_5.setTitle(_translate("Dialog", "Alınan Orjinal Gürüntü", None))
        self.btnResimYukle.setText(_translate("Dialog", "Resim Yükle", None))
        self.groupBox_6.setTitle(_translate("Dialog", "Sonuç ", None))
        self.groupBox_7.setTitle(_translate("Dialog", "Piksel Bilgi Ekranı", None))
        self.groupBox_13.setTitle(_translate("Dialog", "Pixel Girişi", None))
        self.btnPikselGoster.setText(_translate("Dialog", "Pikelsleri Göster", None))
        self.label_65.setText(_translate("Dialog", "Yükseklik", None))
        self.label_66.setText(_translate("Dialog", "Genişlik", None))
        self.label_27.setText(_translate("Dialog", "Piksel Değerinin Gösterileceği Aralık Değerleri", None))
        self.groupBox_15.setTitle(_translate("Dialog", "Histogram", None))
        self.label_23.setText(_translate("Dialog", "Orjinal Görüntünün  Histogramı", None))
        self.label_26.setText(_translate("Dialog", "Sonuç Görüntüsünün  Histogramı", None))
        self.btnHistogram.setText(_translate("Dialog", "Histogram Grafikleri", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_12), _translate("Dialog", "Temel İşlemler", None))
        self.groupBox_3.setTitle(_translate("Dialog", "İşlem Yapılacak Orijinal Resim ", None))
        self.btnResimYukle2.setText(_translate("Dialog", "Resim Yükle", None))
        self.groupBox_4.setTitle(_translate("Dialog", "İşlemler", None))
        self.btnCanny.setText(_translate("Dialog", "Canny", None))
        self.btnSobel.setText(_translate("Dialog", "Sobel", None))
        self.btnPrewit.setText(_translate("Dialog", "Prewit", None))
        self.btnTreshold.setText(_translate("Dialog", "Threshold", None))
        self.groupBox_8.setTitle(_translate("Dialog", "Yapılan İşlemin Sonucu", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_13), _translate("Dialog", "Filtreleme", None))
        self.groupBox_9.setTitle(_translate("Dialog", "Orjinal Görüntü", None))
        self.btnLabelingYukle.setText(_translate("Dialog", "Resim Yükle", None))
        self.groupBox_10.setTitle(_translate("Dialog", "Seçilen Görüntü", None))
        self.groupBox_11.setTitle(_translate("Dialog", "Kenar Alma ", None))
        self.btnLabeling.setText(_translate("Dialog", "Labeling", None))
        self.groupBox_12.setTitle(_translate("Dialog", "Karşılaştırma Seçim Ekranı ", None))
        self.groupBox.setTitle(_translate("Dialog", "Karşılaştırma Yapılacak Sekili sec", None))
        self.rbtnKare.setText(_translate("Dialog", "Kare", None))
        self.rbtnDikdortgen.setText(_translate("Dialog", "Dikdörtgen", None))
        self.groupBox_57.setTitle(_translate("Dialog", "Kontrol ", None))
        self.btnLabelingKarsilastir.setText(_translate("Dialog", "Karşılaştır ", None))
        self.label_25.setText(_translate("Dialog", "Krşılaştırma Sonucu : ", None))
        self.groupBox_37.setTitle(_translate("Dialog", "Bulunan Şekil Listesi", None))
        self.label_33.setText(_translate("Dialog", "Bulunan Görüntüler :", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_14), _translate("Dialog", "Labeling", None))
        self.groupBox_58.setTitle(_translate("Dialog", "Orjinal Görüntü", None))
        self.btnHistogramYukle.setText(_translate("Dialog", "Resim Yükle", None))
        self.groupBox_59.setTitle(_translate("Dialog", "Benzerlik İşlemi Yapılacak Ressim", None))
        self.groupBox_60.setTitle(_translate("Dialog", "Benzerlik ", None))
        self.btnHistogramKarsilastir.setText(_translate("Dialog", "Karşılaştır", None))
        self.groupBox_61.setTitle(_translate("Dialog", "Benzerlik Karşılaştırma Oranları", None))
        self.label_2.setText(_translate("Dialog", "Benzerlik Oranları", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_15), _translate("Dialog", "Histogram Eşitleme", None))
        self.groupBox_62.setTitle(_translate("Dialog", "Benzerlik Oranıları ", None))
        self.btnGurultuBenzerlikHesapla.setText(_translate("Dialog", " Hesapalama", None))
        self.lblSsim.setText(_translate("Dialog", "SSIM  :", None))
        self.lblMse.setText(_translate("Dialog", "MSE  :", None))
        self.groupBox_63.setTitle(_translate("Dialog", "Orjinal Görüntü", None))
        self.btnGurultuYukle.setText(_translate("Dialog", "Resim Yükle", None))
        self.groupBox_64.setTitle(_translate("Dialog", "Görültü Oluştur ", None))
        self.btnGurultuOlustur.setText(_translate("Dialog", "Oluştur", None))
        self.label.setText(_translate("Dialog", "Gürültü Oranı :", None))
        self.groupBox_65.setTitle(_translate("Dialog", "Görültülü Resim ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_16), _translate("Dialog", "Gürültü", None))
        self.groupBox_66.setTitle(_translate("Dialog", "1. Resim", None))
        self.btnMantikYukle1Resim.setText(_translate("Dialog", "Resim Yükle", None))
        self.groupBox_68.setTitle(_translate("Dialog", "İşlemler", None))
        self.lb_ssim_11.setText(_translate("Dialog", "İşlem Seçiniz ", None))
        self.cbMantik.setItemText(0, _translate("Dialog", "AND", None))
        self.cbMantik.setItemText(1, _translate("Dialog", "OR", None))
        self.cbMantik.setItemText(2, _translate("Dialog", "XOR", None))
        self.cbMantik.setItemText(3, _translate("Dialog", "NOT-SOL", None))
        self.cbMantik.setItemText(4, _translate("Dialog", "NOT-SAĞ", None))
        self.btnMantikGoster.setText(_translate("Dialog", "Göster", None))
        self.groupBox_69.setTitle(_translate("Dialog", "Sonuç", None))
        self.groupBox_67.setTitle(_translate("Dialog", "2. Resim", None))
        self.btnMantikYukle2Resim.setText(_translate("Dialog", "Resim Yükle", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_17), _translate("Dialog", "Mantık İşlemleri", None))
        self.groupBox_70.setTitle(_translate("Dialog", "Orjinal Görüntü", None))
        self.btnErosionYukle.setText(_translate("Dialog", "Resim Yükle", None))
        self.groupBox_71.setTitle(_translate("Dialog", "İşlemler", None))
        self.btnDilation.setText(_translate("Dialog", "Dilation", None))
        self.btnErosion.setText(_translate("Dialog", "Erosion", None))
        self.groupBox_72.setTitle(_translate("Dialog", "İşlem Sonucu", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_18), _translate("Dialog", "Erosion - Dilation", None))
        self.groupBox_19.setTitle(_translate("Dialog", "Gürüntü Ekleme", None))
        self.btnTemplateYukle.setText(_translate("Dialog", "Resim Yükle", None))
        self.groupBox_21.setTitle(_translate("Dialog", "TM  CCOEFF  NORMED   ", None))
        self.label_4.setText(_translate("Dialog", "BENZERLİK ORANI :", None))
        self.groupBox_25.setTitle(_translate("Dialog", "TM  CCORR  NORMED   ", None))
        self.label_5.setText(_translate("Dialog", "BENZERLİK ORANI :", None))
        self.groupBox_28.setTitle(_translate("Dialog", "TM  SQDIFF ", None))
        self.label_8.setText(_translate("Dialog", "BENZERLİK ORANI :", None))
        self.groupBox_22.setTitle(_translate("Dialog", "İşlemler ", None))
        self.label_21.setText(_translate("Dialog", "Görüntüler", None))
        self.label_22.setText(_translate("Dialog", "Aranacak Görüntüler", None))
        self.btnTemplate.setText(_translate("Dialog", "Template Matching", None))
        self.groupBox_27.setTitle(_translate("Dialog", " TM  CCOEFF ", None))
        self.label_32.setText(_translate("Dialog", "TM_CCOEFF_NORMED", None))
        self.label_7.setText(_translate("Dialog", "BENZERLİK ORANI :", None))
        self.groupBox_26.setTitle(_translate("Dialog", "TM  CCORR  ", None))
        self.lbl.setText(_translate("Dialog", "BENZERLİK ORANI :", None))
        self.groupBox_20.setTitle(_translate("Dialog", " TM SQDIFF  NORMED     ", None))
        self.label_3.setText(_translate("Dialog", "BENZERLİK ORANI :", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_19), _translate("Dialog", "Template Matching", None))
        self.groupBox_56.setTitle(_translate("Dialog", "Mevcut Kişiler", None))
        self.groupBox_90.setTitle(_translate("Dialog", "Kişileri Bul", None))
        self.btnYuzTanimaKisiBul.setText(_translate("Dialog", " Bul", None))
        self.groupBox_93.setTitle(_translate("Dialog", "Kayıt Edilecek Kişi İsmi", None))
        self.btnYuzIsimKaydet.setText(_translate("Dialog", "Kaydet", None))
        self.btnYuzEkleme.setText(_translate("Dialog", "Ekleme", None))
        self.btnYuzTanimaYukle1.setText(_translate("Dialog", "Yoklama ", None))
        self.groupBox_89.setTitle(_translate("Dialog", "Ekleme İşlemleri", None))
        self.groupBox_92.setTitle(_translate("Dialog", "Kişileri Bul", None))
        self.btnKisiBul.setText(_translate("Dialog", "Bul", None))
        self.label_9.setText(_translate("Dialog", "Uyarı :", None))
        self.groupBox_91.setTitle(_translate("Dialog", "Bulunan Kişi Listesi", None))
        self.btnYuzTanimaYukle2.setText(_translate("Dialog", "Sınıf Mevcudu", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_20), _translate("Dialog", "Yüz Tanıma", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

